import type { VerificationStatus, VerificationEvidence } from '../../types'
import type { AgentRuntimeResult } from '../types'

export interface VerificationCheck {
  name: string
  passed: boolean
  details: string
}

export interface AcceptanceCriterionCheck {
  name: string
  passed: boolean
  details: string
}

export interface VerificationInput {
  runtimeResult?: AgentRuntimeResult
  testOutput?: string
  testExitCode?: number
  typecheckPassed?: boolean
  buildPassed?: boolean
  acceptanceCriteria?: AcceptanceCriterionCheck[]
  artifactChecks?: VerificationCheck[]
  diffCount?: number
  securityPassed?: boolean
}

export interface VerificationReport {
  status: VerificationStatus
  score: number // 0 - 100
  checks: VerificationCheck[]
  evidence: VerificationEvidence[]
  summaryNotes: string
}

export class VerificationEngine {
  /**
   * Evaluates structured verification evidence against quality gate policies
   */
  static evaluate(input: VerificationInput): VerificationReport {
    const checks: VerificationCheck[] = []
    const evidence: VerificationEvidence[] = []

    let hasFatalFailure = false
    let hasWarning = false

    // 1. Security Compliance Quality Gate (Mandatory)
    if (input.securityPassed !== undefined) {
      const passed = input.securityPassed === true
      if (!passed) hasFatalFailure = true
      checks.push({
        name: 'Security & Sandbox Boundary Compliance',
        passed,
        details: passed
          ? 'Zero sandbox boundary violations or path traversal attempts detected.'
          : 'Security check failed: unauthorized file or command access detected.'
      })
      evidence.push({
        type: 'security',
        name: 'Sandbox Policy Compliance',
        passed,
        details: passed ? 'Passed safe boundary audit' : 'Failed security validation'
      })
    }

    // 2. Test Suite Execution (Mandatory if executed)
    if (input.testExitCode !== undefined) {
      const testsPassed = input.testExitCode === 0
      if (!testsPassed) hasFatalFailure = true
      checks.push({
        name: 'Automated Test Suite',
        passed: testsPassed,
        details: testsPassed
          ? 'All unit/integration tests passed successfully with 0 failures.'
          : `Test suite execution failed with exit code ${input.testExitCode}.`
      })
      evidence.push({
        type: 'test',
        name: 'Unit / Integration Tests',
        passed: testsPassed,
        details: input.testOutput || (testsPassed ? 'Exit code 0' : `Exit code ${input.testExitCode}`),
        command: 'vitest run'
      })
    }

    // 3. Static Typecheck (Mandatory if executed)
    if (input.typecheckPassed !== undefined) {
      const typePassed = input.typecheckPassed === true
      if (!typePassed) hasFatalFailure = true
      checks.push({
        name: 'TypeScript Strict Typecheck',
        passed: typePassed,
        details: typePassed
          ? 'Type verification clean with 0 type errors.'
          : 'Static type checking reported errors.'
      })
      evidence.push({
        type: 'typecheck',
        name: 'TypeScript Validation',
        passed: typePassed,
        details: typePassed ? '0 errors (strict mode)' : 'Typecheck errors found',
        command: 'vue-tsc --noEmit'
      })
    }

    // 4. Production Build (Mandatory if executed)
    if (input.buildPassed !== undefined) {
      const bPassed = input.buildPassed === true
      if (!bPassed) hasFatalFailure = true
      checks.push({
        name: 'Production Build & Bundling',
        passed: bPassed,
        details: bPassed
          ? 'Vite production build and PWA bundle succeeded.'
          : 'Production build compilation failed.'
      })
      evidence.push({
        type: 'build',
        name: 'Production Build Bundle',
        passed: bPassed,
        details: bPassed ? 'Clean bundle generation' : 'Build failed',
        command: 'vite build'
      })
    }

    // 5. Acceptance Criteria Validation (Mandatory)
    if (input.acceptanceCriteria && input.acceptanceCriteria.length > 0) {
      for (const crit of input.acceptanceCriteria) {
        if (!crit.passed) hasFatalFailure = true
        checks.push({
          name: `Criteria: ${crit.name}`,
          passed: crit.passed,
          details: crit.details
        })
        evidence.push({
          type: 'criteria',
          name: crit.name,
          passed: crit.passed,
          details: crit.details
        })
      }
    } else if (input.runtimeResult !== undefined) {
      // Default baseline criteria check from output if runtimeResult was provided
      const hasOutput = input.runtimeResult.output.trim().length > 0
      checks.push({
        name: 'Deliverable Output Generation',
        passed: hasOutput,
        details: hasOutput
          ? 'Agent produced valid deliverable output content.'
          : 'No output generated by agent.'
      })
      evidence.push({
        type: 'criteria',
        name: 'Deliverable Output',
        passed: hasOutput,
        details: hasOutput ? 'Content generated' : 'Empty output'
      })
      if (!hasOutput) hasFatalFailure = true
    }

    // 6. Artifact & File Change Verification
    if (input.artifactChecks && input.artifactChecks.length > 0) {
      for (const art of input.artifactChecks) {
        checks.push(art)
        evidence.push({
          type: 'artifact',
          name: art.name,
          passed: art.passed,
          details: art.details
        })
        if (!art.passed) hasWarning = true
      }
    } else if (input.diffCount !== undefined) {
      const hasDiffs = input.diffCount > 0
      checks.push({
        name: 'Deliverable File Changes',
        passed: true,
        details: hasDiffs
          ? `${input.diffCount} file modifications verified.`
          : 'Read-only analysis task verified with structured deliverable report.'
      })
      evidence.push({
        type: 'diff',
        name: 'File Modifications',
        passed: true,
        details: hasDiffs ? `${input.diffCount} files modified` : 'Read-only execution'
      })
    }

    const totalPassed = checks.filter((c) => c.passed).length
    const score = checks.length > 0 ? Math.round((totalPassed / checks.length) * 100) : 100

    // Quality Gate Decision Logic:
    let status: VerificationStatus = 'Pending'
    if (hasFatalFailure) {
      status = 'Failed'
    } else if (hasWarning || score < 100) {
      status = 'Warning'
    } else {
      status = 'Passed'
    }

    const summaryNotes = `Quality Gate ${status}: ${totalPassed}/${checks.length} assertions passed (Score: ${score}%).`

    return {
      status,
      score,
      checks,
      evidence,
      summaryNotes
    }
  }
}
